### ISSUE TITLE
FR10. Leaderboard 

### ISSUE THREAD

**Issue by mhazadegan** [WSU-4110/Tecducate#10]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-05f039a9-7fff-fa7c-6565-3ad92fd9bdcb"><div dir="ltr" style="margin-left:0pt;" align="left">

FR10. Leaderboard
--
Goal: Motivate the user to continue to learn and grow.
Stakeholders: Elderly people
On the profile page, there will be a leader board that displays the top 3 users based on their proficiency level. This leader board will show their username, proficiency level and their most played lesson type. This will boost the engagement rate by up to 3% ensuring that our users are participating in our app for longer periods.
Origin: Discussed during our in-person meeting on 9/18/2023
Version: 1.0 | Date: September 18th, 2023 | Priority: 7

</div><br /></b>
</body>
</html>

**Comment by GeoT82** [comment]
Added SQL database integration
