### ISSUE TITLE
FR2: Delete user profile 

### ISSUE THREAD

**Issue by Susmita-Rani-Ghosh** [WSU-4110/Tecducate#17]
**Goal:** provide users with the capability to delete their profiles from the application.

**Stakeholders:** Elderly People

**Description:** Our users will be able to delete all of their personal information from their profiles. This gives the user more control over their data, which gives them both peace of mind and trust towards our website.

**Origin:** Discussed during our virtual meeting on 9/16/2023.

**Version:** 1.0

**Date:** 9/18/2023

**Priority:** 5

**Comment by mhazadegan** [comment]
Delete function properly working and deleting entire profile

**Comment by mhazadegan** [comment]
Delete function properly working and deleting entire profile
