### ISSUE TITLE
FR14. Dynamic Lesson Database

### ISSUE THREAD

**Issue by mariasam16** [WSU-4110/Tecducate#4]
|FR14.  Dynamic Lesson Database|
|---|
|**Goal**: Allows users to view what to learn next and see it dynamically. 
**Stakeholders:** Elderly people|
| **Description:** Users will be able to interact with a menu that displays the other lessons so that they can continue strengthening their knowledge. Allowing the user to have a sense of direction as to where to go next from one lesson to another. These lesson topics are dynamically accessed from our database and displayed on our lesson template|
| **Origin:** Discussed during our in-person meeting on 9/18/2023|
| **Version:** 1.0 |
|**Date:** 09/18/2023
| **Priority:** 6 |

**Comment by GeoT82** [comment]
Completed
