### ISSUE TITLE
Bug: Profile page is not showing user Data

### ISSUE THREAD

**Issue by Susmita-Rani-Ghosh** [WSU-4110/Tecducate#61]
1. The sql lesson code should have some details and samples.
2. The functionalities to make display user info on the profile page is missing from the userDAO and controlservlet file

**Comment by mhazadegan** [comment]
Dynamic user info is now shown on the profile page

**Comment by Susmita-Rani-Ghosh** [comment]
Link to the commit
[https://github.com/WSU-4110/Tecducate/commit/7c61baf3ebc22e61ac7795d9af9440254b7015f1](url)
