### ISSUE TITLE
FR7.  Deny Incorrect input 

### ISSUE THREAD

**Issue by mhazadegan** [WSU-4110/Tecducate#7]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-4ede9673-7fff-7fc1-4201-b70379cadd82"><div dir="ltr" style="margin-left:0pt;" align="left">

Goal: Provide feedback to the users when inserted incorrect information.
--
Stakeholders: elderly people
This will provide visual and written feedback to the users when they insert incorrect email address, phone number or password. Then the user can use this information to provide valid input to ensure that they can either make an account or use one.
Origin: Discussed during our virtual meeting on 9/16/2023
Version: 1.0 | Date:  9/16/2023 | Priority: 7

</div></b>
</body>
</html>

**Comment by Susmita-Rani-Ghosh** [comment]
closed. Register and log in functions check if the user exits or incorrect input has been provided and denies the incorrect input.
